service: auction-service

plugins:
  - serverless-pseudo-parameters
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    alias:
      '@': './src'

functions:
  create-auction:
    handler: src/presentation/handlers/create-auction.handler
    events:
      - http:
          method: POST
          path: /auction
  get-auction-by-id:
    handler: src/presentation/handlers/get-auction-by-id.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  get-auctions:
    handler: src/presentation/handlers/get-auctions.handler
    events:
      - http:
          method: GET
          path: /auctions
  place-bid:
    handler: src/presentation/handlers/place-bid.handler
    events:
      - http:
          method: POST
          path: /auction/{id}/bid
  process-auctions:
    handler: src/presentation/handlers/process-auctions.handler
    events:
      - schedule: rate(1 minute)
