service: auction-service

plugins:
  - serverless-iam-roles-per-function
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1

resources:
  Resources:
    MailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.mailQueue.name}
  Outputs:
    MailQueueUrl:
      Description: URL da fila SQS de e-mails (use em SQS_QUEUE_URL para testes locais)
      Value:
        Ref: MailQueue
      Export:
        Name: ${self:service}-${self:provider.stage}-MailQueueUrl

custom:
  mailQueue:
    name: mail-queue-${self:provider.stage}
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    alias:
      '@': './src'

functions:
  authorizer:
    handler: src/presentation/authorizer/handler.handler
    environment:
      JWT_SECRET: ${env:JWT_SECRET, 'secret'}

  create-auction:
    handler: src/presentation/handlers/create-auction.handler
    events:
      - http:
          method: POST
          path: /auction
          authorizer:
            name: authorizer
            type: request
            resultTtlInSeconds: 300

  get-auction-by-id:
    handler: src/presentation/handlers/get-auction-by-id.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          authorizer:
            name: authorizer
            type: request
            resultTtlInSeconds: 300

  get-auctions:
    handler: src/presentation/handlers/get-auctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          authorizer:
            name: authorizer
            type: request
            resultTtlInSeconds: 300

  place-bid:
    handler: src/presentation/handlers/place-bid.handler
    events:
      - http:
          method: POST
          path: /auction/{id}/bid
          authorizer:
            name: authorizer
            type: request
            resultTtlInSeconds: 300

  process-auctions:
    handler: src/presentation/handlers/process-auctions.handler
    events:
      - schedule: rate(1 minute)
    environment:
      SQS_QUEUE_URL:
        Ref: MailQueue
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          Fn::GetAtt:
            - MailQueue
            - Arn

  send-email:
    handler: src/presentation/handlers/sendEmail.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MailQueue
              - Arn
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendEmail
        Resource: '*'
      - Effect: Allow
        Action:
          - sqs:ReceiveMessage
        Resource:
          Fn::GetAtt:
            - MailQueue
            - Arn
